### ISSUE TITLE
Possible deadlock in the framework with the search test

### ISSUE THREAD

**Issue by znAaron** [emichael/dslabs#43]
When running some students' solutions with the latest dslab framework, I noticed that the search test would get stuck. e.g. A 30 seconds timeout test would run forever. Using jstack to look into the threads, I found a deadlock between the search threads. It seems they are all blocked at Search.java:499 `discovered.add(successor.wrapped())`.

The following is printed by jstack

Found one Java-level deadlock:
=============================
"Thread-12":
  waiting to lock monitor 0x00007fa138008f00 (object 0x0000000780b1c3f8, a java.util.Hashtable),
  which is held by "Thread-17"

"Thread-17":
  waiting to lock monitor 0x00007fa13800f400 (object 0x0000000780b2a3b0, a java.util.Hashtable),
  which is held by "Thread-16"

"Thread-16":
  waiting to lock monitor 0x00007fa138009400 (object 0x0000000781588248, a java.util.Hashtable),
  which is held by "Thread-14"

"Thread-14":
  waiting to lock monitor 0x00007fa13800f400 (object 0x0000000780b2a3b0, a java.util.Hashtable),
  which is held by "Thread-16"

Java stack information for the threads listed above:
===================================================
"Thread-12":
	at java.util.Hashtable.hashCode(java.base@14.0.2/Hashtable.java:864)
	- waiting to lock <0x0000000780b1c3f8> (a java.util.Hashtable)
	at dslabs.primarybackup.PBServer.hashCode(PBServer.java:19)
	at java.util.Objects.hashCode(java.base@14.0.2/Objects.java:117)
	at java.util.HashMap$Node.hashCode(java.base@14.0.2/HashMap.java:298)
	at java.util.AbstractMap.hashCode(java.base@14.0.2/AbstractMap.java:527)
	at dslabs.framework.testing.AbstractState.hashCode(AbstractState.java:49)
	at dslabs.framework.testing.search.SearchState.hashCode(SearchState.java:68)
	at dslabs.framework.testing.search.SearchState$SearchEquivalenceWrappedSearchState.hashCode(SearchState.java:623)
	at java.util.concurrent.ConcurrentHashMap.putVal(java.base@14.0.2/ConcurrentHashMap.java:1012)
	at java.util.concurrent.ConcurrentHashMap.put(java.base@14.0.2/ConcurrentHashMap.java:1006)
	at java.util.Collections$SetFromMap.add(java.base@14.0.2/Collections.java:5654)
	at dslabs.framework.testing.search.BFS.exploreNode(Search.java:499)
	at dslabs.framework.testing.search.BFS.lambda$getWorker$0(Search.java:479)
	at dslabs.framework.testing.search.BFS$$Lambda$133/0x0000000800c07440.run(Unknown Source)
	at dslabs.framework.testing.search.Search.lambda$run$0(Search.java:275)
	at dslabs.framework.testing.search.Search$$Lambda$132/0x0000000800c07040.run(Unknown Source)
	at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)
"Thread-17":
	at java.util.Hashtable.size(java.base@14.0.2/Hashtable.java:248)
	- waiting to lock <0x0000000780b2a3b0> (a java.util.Hashtable)
	at java.util.Hashtable.equals(java.base@14.0.2/Hashtable.java:822)
	- locked <0x0000000780b1c3f8> (a java.util.Hashtable)
	at dslabs.primarybackup.PBServer.equals(PBServer.java:19)
	at java.util.AbstractMap.equals(java.base@14.0.2/AbstractMap.java:493)
	at dslabs.framework.testing.AbstractState.equals(AbstractState.java:49)
	at dslabs.framework.testing.search.SearchState.equals(SearchState.java:68)
	at java.util.Objects.equals(java.base@14.0.2/Objects.java:78)
	at dslabs.framework.testing.search.SearchState$SearchEquivalenceWrappedSearchState.equals(SearchState.java:606)
	at java.util.concurrent.ConcurrentHashMap.putVal(java.base@14.0.2/ConcurrentHashMap.java:1039)
	- locked <0x00000007814a8c08> (a java.util.concurrent.ConcurrentHashMap$Node)
	at java.util.concurrent.ConcurrentHashMap.put(java.base@14.0.2/ConcurrentHashMap.java:1006)
	at java.util.Collections$SetFromMap.add(java.base@14.0.2/Collections.java:5654)
	at dslabs.framework.testing.search.BFS.exploreNode(Search.java:499)
	at dslabs.framework.testing.search.BFS.lambda$getWorker$0(Search.java:479)
	at dslabs.framework.testing.search.BFS$$Lambda$133/0x0000000800c07440.run(Unknown Source)
	at dslabs.framework.testing.search.Search.lambda$run$0(Search.java:275)
	at dslabs.framework.testing.search.Search$$Lambda$132/0x0000000800c07040.run(Unknown Source)
	at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)
"Thread-16":
	at java.util.Hashtable.size(java.base@14.0.2/Hashtable.java:248)
	- waiting to lock <0x0000000781588248> (a java.util.Hashtable)
	at java.util.Hashtable.equals(java.base@14.0.2/Hashtable.java:822)
	- locked <0x0000000780b2a3b0> (a java.util.Hashtable)
	at dslabs.primarybackup.PBServer.equals(PBServer.java:19)
	at java.util.AbstractMap.equals(java.base@14.0.2/AbstractMap.java:493)
	at dslabs.framework.testing.AbstractState.equals(AbstractState.java:49)
	at dslabs.framework.testing.search.SearchState.equals(SearchState.java:68)
	at java.util.Objects.equals(java.base@14.0.2/Objects.java:78)
	at dslabs.framework.testing.search.SearchState$SearchEquivalenceWrappedSearchState.equals(SearchState.java:606)
	at java.util.concurrent.ConcurrentHashMap.putVal(java.base@14.0.2/ConcurrentHashMap.java:1039)
	- locked <0x0000000781565b00> (a java.util.concurrent.ConcurrentHashMap$Node)
	at java.util.concurrent.ConcurrentHashMap.put(java.base@14.0.2/ConcurrentHashMap.java:1006)
	at java.util.Collections$SetFromMap.add(java.base@14.0.2/Collections.java:5654)
	at dslabs.framework.testing.search.BFS.exploreNode(Search.java:499)
	at dslabs.framework.testing.search.BFS.lambda$getWorker$0(Search.java:479)
	at dslabs.framework.testing.search.BFS$$Lambda$133/0x0000000800c07440.run(Unknown Source)
	at dslabs.framework.testing.search.Search.lambda$run$0(Search.java:275)
	at dslabs.framework.testing.search.Search$$Lambda$132/0x0000000800c07040.run(Unknown Source)
	at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)
"Thread-14":
	at java.util.Hashtable.size(java.base@14.0.2/Hashtable.java:248)
	- waiting to lock <0x0000000780b2a3b0> (a java.util.Hashtable)
	at java.util.Hashtable.equals(java.base@14.0.2/Hashtable.java:822)
	- locked <0x0000000781588248> (a java.util.Hashtable)
	at dslabs.primarybackup.PBServer.equals(PBServer.java:19)
	at java.util.AbstractMap.equals(java.base@14.0.2/AbstractMap.java:493)
	at dslabs.framework.testing.AbstractState.equals(AbstractState.java:49)
	at dslabs.framework.testing.search.SearchState.equals(SearchState.java:68)
	at java.util.Objects.equals(java.base@14.0.2/Objects.java:78)
	at dslabs.framework.testing.search.SearchState$SearchEquivalenceWrappedSearchState.equals(SearchState.java:606)
	at java.util.concurrent.ConcurrentHashMap.putVal(java.base@14.0.2/ConcurrentHashMap.java:1039)
	- locked <0x0000000780f7f258> (a java.util.concurrent.ConcurrentHashMap$Node)
	at java.util.concurrent.ConcurrentHashMap.put(java.base@14.0.2/ConcurrentHashMap.java:1006)
	at java.util.Collections$SetFromMap.add(java.base@14.0.2/Collections.java:5654)
	at dslabs.framework.testing.search.BFS.exploreNode(Search.java:499)
	at dslabs.framework.testing.search.BFS.lambda$getWorker$0(Search.java:479)
	at dslabs.framework.testing.search.BFS$$Lambda$133/0x0000000800c07440.run(Unknown Source)
	at dslabs.framework.testing.search.Search.lambda$run$0(Search.java:275)
	at dslabs.framework.testing.search.Search$$Lambda$132/0x0000000800c07040.run(Unknown Source)
	at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)

Found 1 deadlock.

**Comment by emichael** [comment]
See https://github.com/emichael/dslabs/blob/9b1ff69f91ca211761aff4a3d13b319d85d4b33f/handout-files/README.md?plain=1#L403-L408
